### ISSUE TITLE
jprime build issues

### ISSUE THREAD

**Issue by gtiley** [arvestad/jprime#12]
I tried building my own jprime jar but ran into some issues. Specifically, the warnings i received when running mvn package are:
[WARNING] The POM for jfree:jfreechart:jar:1.0.8 is missing, no dependency information available
[WARNING] The POM for org:mdsj:jar:0.2.0 is missing, no dependency information available

I'm not a java guy, so it's difficult for me to tell if I'm missing some dependencies or if these are changes that need to be made to the pom.

In lieu of of building my own jar, are pre-packaged jars still available, as when jprime was hosted on google code? 

I appreciate any help - George

**Comment by arvestad** [comment]
Sadly, I am not a java person either! :-) I am making a jar file available in a moment.

**Comment by arvestad** [comment]
There is now a link to a Dropbox folder where I have put our latest build in the file README.md (converted README.txt to README.md). Let me know if there are still issues with this!

**Comment by gtiley** [comment]
Everything works great, thank you!
